### ISSUE TITLE
Pre requisites section not available

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/open-edx-industrial-electric-drives-lab#1]
Pre requisites section not available, flash plugin is required to run the simulations.

**Comment by sanchita-dixit** [comment]
There is no pre requisites section given in the lab also. The Flash plugin is required even if I tried uploading the swf files locally on open edx platform itself. We cannot create a new section of pre requisites if it is not present in the original lab. All the experiment simulations are in swf format only which leads to a download pop up.

**Comment by sravanthimodepu** [comment]
Closing the issue.
