### ISSUE TITLE
'exp_id' and 'exp_name' not available

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/open-edx-industrial-electric-drives-lab#2]
'exp_id' and 'exp_name' not available
References:
Lab URL: [http://ied-nitk.vlabs.ac.in](http://ied-nitk.vlabs.ac.in)
Lab Id: ee08
Lab Name: Industrial Electric Drives
LDS URL: [http://lds-alpha.base4.vlabs.ac.in/labs?lab_id=ee08](http://lds-alpha.base4.vlabs.ac.in/labs?lab_id=ee08)

**Comment by sravanthimodepu** [comment]
In all the simulations, code to perform the experiment was not added properly. Corrected the code in all the simulations to get analytics usage.
Arranged all the sections in the experiments in a proper order as  "Theory, Procedure, Simulator, Assignment, Self-evaluation, Quiz, Videos, Reference, Feedback".

**Comment by sravanthimodepu** [comment]
For the 1st two experiments, there are no exp_ids in LDS.

**Comment by sravanthimodepu** [comment]
Updated all the ids and able to get the analytics usage. Hence closing the issue.
